/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontend;

import java.awt.Image;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;

import Backend.Gauss;
import Backend.Lu;

/**
 *
 * @author Daniel
 */
public class Matrix_UI extends javax.swing.JFrame {

    /**
     *
     */
    private static final long serialVersionUID = 1L;

    /**
     * Creates new form Matrix_UI
     */
    public Matrix_UI() {
        initComponents();
        myConfig();// personal purpose
    }

    private void myConfig() {
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.setLocationRelativeTo(null);

        // Rezising the img
        ImageIcon icon = new ImageIcon("src/main/java/images/CUNOC_logo.png");
        this.cunoc_logo.setOpaque(true);
        this.cunoc_logo.setIcon(new ImageIcon(icon.getImage().getScaledInstance(130, 130, Image.SCALE_SMOOTH)));
        this.cunoc_logo.setBackground(null);

        try {
            UIManager.setLookAndFeel("com.jtattoo.plaf.graphite.GraphiteLookAndFeel");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Matrix_UI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(Matrix_UI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(Matrix_UI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(Matrix_UI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        container = new javax.swing.JPanel();
        Header_panel = new javax.swing.JPanel();
        cunoc_logo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Footer_panel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        results_table = new javax.swing.JTable();
        right_panel = new javax.swing.JPanel();
        gauss_resolve_butotn = new javax.swing.JButton();
        gauss_jordan_button = new javax.swing.JButton();
        gauss_seidel_button = new javax.swing.JButton();
        Left_panel = new javax.swing.JPanel();
        regresion = new javax.swing.JButton();
        lu_method_button = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        Main_panel = new javax.swing.JPanel();
        a00_cell = new javax.swing.JTextField();
        a01_cell = new javax.swing.JTextField();
        a02_cell = new javax.swing.JTextField();
        r0_cell = new javax.swing.JTextField();
        a10_cell = new javax.swing.JTextField();
        a11_cell = new javax.swing.JTextField();
        a12_cell = new javax.swing.JTextField();
        r1_cell = new javax.swing.JTextField();
        a20_cell = new javax.swing.JTextField();
        a21_cell = new javax.swing.JTextField();
        a22_cell = new javax.swing.JTextField();
        r2_cell = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(6);

        container.setVerifyInputWhenFocusTarget(false);
        container.setLayout(new java.awt.BorderLayout());

        Header_panel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Daniel Eduardo Bautista Fuentes");

        jLabel2.setText("201930588 Mate Aplicada III");

        javax.swing.GroupLayout Header_panelLayout = new javax.swing.GroupLayout(Header_panel);
        Header_panel.setLayout(Header_panelLayout);
        Header_panelLayout.setHorizontalGroup(Header_panelLayout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Header_panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(Header_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2).addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        167, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 639, Short.MAX_VALUE)
                        .addComponent(cunoc_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 130,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap()));
        Header_panelLayout.setVerticalGroup(Header_panelLayout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Header_panelLayout.createSequentialGroup().addContainerGap()
                        .addGroup(Header_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(Header_panelLayout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel2).addGap(0, 68, Short.MAX_VALUE))
                                .addComponent(cunoc_logo, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap()));

        container.add(Header_panel, java.awt.BorderLayout.PAGE_START);

        Footer_panel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setText("Resultados");

        results_table.setModel(new javax.swing.table.DefaultTableModel(new Object[][] { { null, null, null } },
                new String[] { "Valor 1", "Valor 2", "Valor 3" }) {
            /**
             *
             */
            private static final long serialVersionUID = 1L;
            Class[] types = new Class[] { java.lang.Long.class, java.lang.Object.class, java.lang.Object.class };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }
        });
        jScrollPane1.setViewportView(results_table);

        javax.swing.GroupLayout Footer_panelLayout = new javax.swing.GroupLayout(Footer_panel);
        Footer_panel.setLayout(Footer_panelLayout);
        Footer_panelLayout.setHorizontalGroup(Footer_panelLayout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Footer_panelLayout.createSequentialGroup().addContainerGap().addGroup(Footer_panelLayout
                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 936, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Footer_panelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE).addComponent(jLabel3).addGap(351, 351, 351)))
                        .addContainerGap()));
        Footer_panelLayout
                .setVerticalGroup(
                        Footer_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
                                Footer_panelLayout.createSequentialGroup().addGap(6, 6, 6).addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 45,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(24, Short.MAX_VALUE)));

        container.add(Footer_panel, java.awt.BorderLayout.PAGE_END);

        right_panel.setBackground(new java.awt.Color(255, 255, 255));
        right_panel.setLayout(new java.awt.GridLayout(3, 1));

        gauss_resolve_butotn.setText("gauss");
        gauss_resolve_butotn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gauss_resolve_butotnActionPerformed(evt);
            }
        });
        right_panel.add(gauss_resolve_butotn);

        gauss_jordan_button.setText("Gauss J");
        gauss_jordan_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gauss_jordan_buttonActionPerformed(evt);
            }
        });
        right_panel.add(gauss_jordan_button);

        gauss_seidel_button.setText("Seidel");
        gauss_seidel_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gauss_seidel_buttonActionPerformed(evt);
            }
        });
        right_panel.add(gauss_seidel_button);

        container.add(right_panel, java.awt.BorderLayout.LINE_END);

        Left_panel.setBackground(new java.awt.Color(255, 255, 255));
        Left_panel.setLayout(new java.awt.GridLayout(2, 1));

        regresion.setText("regresica");
        regresion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresionActionPerformed(evt);
            }
        });
        Left_panel.add(regresion);

        lu_method_button.setText("Lu");
        lu_method_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lu_method_buttonActionPerformed(evt);
            }
        });
        Left_panel.add(lu_method_button);

        container.add(Left_panel, java.awt.BorderLayout.LINE_START);
        container.add(jSeparator1, java.awt.BorderLayout.CENTER);

        Main_panel.setBackground(new java.awt.Color(255, 255, 255));
        Main_panel.setLayout(new java.awt.GridLayout(3, 3, 5, 5));

        a00_cell.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        a00_cell.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        a00_cell.setText("0");
        Main_panel.add(a00_cell);

        a01_cell.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        a01_cell.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        a01_cell.setText("0");
        Main_panel.add(a01_cell);

        a02_cell.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        a02_cell.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        a02_cell.setText("0");
        Main_panel.add(a02_cell);

        r0_cell.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        r0_cell.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        r0_cell.setText("0");
        Main_panel.add(r0_cell);

        a10_cell.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        a10_cell.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        a10_cell.setText("0");
        Main_panel.add(a10_cell);

        a11_cell.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        a11_cell.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        a11_cell.setText("0");
        a11_cell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a11_cellActionPerformed(evt);
            }
        });
        Main_panel.add(a11_cell);

        a12_cell.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        a12_cell.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        a12_cell.setText("0");
        Main_panel.add(a12_cell);

        r1_cell.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        r1_cell.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        r1_cell.setText("0");
        Main_panel.add(r1_cell);

        a20_cell.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        a20_cell.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        a20_cell.setText("0");
        Main_panel.add(a20_cell);

        a21_cell.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        a21_cell.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        a21_cell.setText("0");
        Main_panel.add(a21_cell);

        a22_cell.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        a22_cell.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        a22_cell.setText("0");
        Main_panel.add(a22_cell);

        r2_cell.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        r2_cell.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        r2_cell.setText("0");
        Main_panel.add(r2_cell);

        container.add(Main_panel, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(container,
                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(container, javax.swing.GroupLayout.DEFAULT_SIZE, 728, Short.MAX_VALUE));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void a11_cellActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_a11_cellActionPerformed
    }// GEN-LAST:event_a11_cellActionPerformed

    private void gauss_resolve_butotnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_gauss_resolve_butotnActionPerformed
        double[][] matrixTmp = getValues();
        Gauss gauss = new Gauss();
        String[] vectorTmp = gauss.resolveByGauss(matrixTmp);
        showResults(vectorTmp);
    }// GEN-LAST:event_gauss_resolve_butotnActionPerformed

    private void regresionActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_regresionActionPerformed
        gauss_resolve_butotnActionPerformed(evt);// uses the same
    }// GEN-LAST:event_regresionActionPerformed

    private void lu_method_buttonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_lu_method_buttonActionPerformed
        double[][] matrix = getValues();
        Lu lu = new Lu();
        String[] vectorTmp = lu.resolveByLu(matrix);
        showResults(vectorTmp);
    }// GEN-LAST:event_lu_method_buttonActionPerformed

    private void gauss_jordan_buttonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_gauss_jordan_buttonActionPerformed
        double[][] matrix = getValues();
        Gauss gauss = new Gauss();
        String[] vectorTmp = gauss.resolveByGaussJordan(matrix);
        showResults(vectorTmp);
    }// GEN-LAST:event_gauss_jordan_buttonActionPerformed

    private void gauss_seidel_buttonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_gauss_seidel_buttonActionPerformed
        double[][] matrixTmp = getValues();
        Gauss gauss = new Gauss();
        String[] vectorTmp = gauss.resolveByGauss(matrixTmp);
        showResults(vectorTmp);
    }// GEN-LAST:event_gauss_seidel_buttonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Footer_panel;
    private javax.swing.JPanel Header_panel;
    private javax.swing.JPanel Left_panel;
    private javax.swing.JPanel Main_panel;
    private javax.swing.JTextField a00_cell;
    private javax.swing.JTextField a01_cell;
    private javax.swing.JTextField a02_cell;
    private javax.swing.JTextField a10_cell;
    private javax.swing.JTextField a11_cell;
    private javax.swing.JTextField a12_cell;
    private javax.swing.JTextField a20_cell;
    private javax.swing.JTextField a21_cell;
    private javax.swing.JTextField a22_cell;
    private javax.swing.JPanel container;
    private javax.swing.JLabel cunoc_logo;
    private javax.swing.JButton gauss_jordan_button;
    private javax.swing.JButton gauss_resolve_butotn;
    private javax.swing.JButton gauss_seidel_button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton lu_method_button;
    private javax.swing.JTextField r0_cell;
    private javax.swing.JTextField r1_cell;
    private javax.swing.JTextField r2_cell;
    private javax.swing.JButton regresion;
    private javax.swing.JTable results_table;
    private javax.swing.JPanel right_panel;
    // End of variables declaration//GEN-END:variables

    // THIS R MY PERSONAL METHODS
    private double[][] getValues() {
        // will return a matix 4 methods
        double[][] matrix = new double[5][6];

        matrix[0][0] = Integer.valueOf(this.a00_cell.getText());
        matrix[0][1] = Integer.valueOf(this.a01_cell.getText());
        matrix[0][2] = Integer.valueOf(this.a02_cell.getText());
        matrix[0][3] = Integer.valueOf(this.r0_cell.getText());
        matrix[1][0] = Integer.valueOf(this.a10_cell.getText());
        matrix[1][1] = Integer.valueOf(this.a11_cell.getText());
        matrix[1][2] = Integer.valueOf(this.a12_cell.getText());
        matrix[1][3] = Integer.valueOf(this.r1_cell.getText());
        matrix[2][0] = Integer.valueOf(this.a20_cell.getText());
        matrix[2][1] = Integer.valueOf(this.a21_cell.getText());
        matrix[2][2] = Integer.valueOf(this.a22_cell.getText());
        matrix[2][3] = Integer.valueOf(this.r2_cell.getText());

        return matrix;
    }

    private void showResults(String[] results) {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Valor 1");
        model.addColumn("Valor 2");
        model.addColumn("Valor 3");
        model.addRow(results);
        this.results_table.setModel(model);
    }

}
